### ISSUE TITLE
Processing-3.3 Compatability

### ISSUE THREAD

**Issue by monkstone** [danbernier/WordCram#69] opened 2017-03-03 11:41 UTC
@danbernier I don't know when it happened but `processing.core.PGraphicsJava2D` has been changed to `processing.awt.PGraphicsJava2D` so the current library doesn't work. However if you subsitute the latest processing `core.jar` into your build and change ocurrences of `processing.core.PGraphicsJava2D` to `processing.awt.PGraphicsJava2D` then it works OK (and build).  For how much longer who can tell, as you seem to have noticed vanilla processing is moving away from awt.
PS I'm thinking of offering a WordCram gem for use with [JRubyArt][] / [propane][], which I would anticipate building with polyglot maven (ruby).

[JRubyArt]:https://github.com/ruby-processing/JRubyArt
[propane]:https://github.com/ruby-processing/propane

**Comment by danbernier** [comment] 2017-03-03 14:55
Hi @monkstone, I'm guessing you downloaded an old version of the WordCram .jar - this issue comes up regularly, lately, I think I must have an old version on the web somewhere. (I just updated the [installation instructions](https://github.com/danbernier/WordCram/wiki/Install), that may have been it.)

IAC, [download v1.0.0](http://wordcram.org/wordcram.1.0.0.zip) and you should be all set. I'll close this ticket, in the expectation that that's the cause, but do re-open if I'm mistaken.

Sure, it'd be great to see WordCram in JRubyArt or propane! [This repo might be worth a look](https://github.com/Nerian/s9-e1), though it's a bit old.

Thanks!

**Closed by danbernier** 2017-03-03 14:55 UTC
